//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerHolidaysLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.HotelActivities = new HashSet<HotelActivity>();
        }
    
        public long ActivityId { get; set; }
        public string ActivityName { get; set; }
    
        public virtual ICollection<HotelActivity> HotelActivities { get; set; }
    }
}
