//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerHolidaysLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.HotelActivities = new HashSet<HotelActivity>();
            this.HotelFacilities = new HashSet<HotelFacility>();
            this.HotelImages = new HashSet<HotelImage>();
            this.HotelTags = new HashSet<HotelTag>();
        }
    
        public long HotelId { get; set; }
        public string HotelName { get; set; }
        public string HotelShortDesc { get; set; }
        public string HotelDesc { get; set; }
        public string AddressLine { get; set; }
        public string Town { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public Nullable<long> CityId { get; set; }
        public string Distric { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<System.TimeSpan> CheckInTimeFrom { get; set; }
        public Nullable<System.TimeSpan> CheckInTimeTo { get; set; }
        public Nullable<System.TimeSpan> CheckOutTimeFrom { get; set; }
        public Nullable<System.TimeSpan> CheckOutTimeTo { get; set; }
        public string CheckInText { get; set; }
        public string CheckOutText { get; set; }
        public Nullable<int> Stars { get; set; }
        public long PropertyTypeId { get; set; }
        public string ChildrenAndExtraBed { get; set; }
        public string Pets { get; set; }
        public string Internet { get; set; }
        public string Parking { get; set; }
        public string LocationGoogleMap { get; set; }
        public string BookingURL { get; set; }
        public string BookingAffiliate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastSyncOn { get; set; }
    
        public virtual ICollection<HotelActivity> HotelActivities { get; set; }
        public virtual ICollection<HotelFacility> HotelFacilities { get; set; }
        public virtual ICollection<HotelImage> HotelImages { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual ICollection<HotelTag> HotelTags { get; set; }
    }
}
