//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerHolidaysLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelImage
    {
        public long HotelImageId { get; set; }
        public long HotelId { get; set; }
        public string ImageUrl { get; set; }
        public bool IsMain { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
