//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerHolidaysLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyType
    {
        public PropertyType()
        {
            this.Hotels = new HashSet<Hotel>();
        }
    
        public long PropertyTypeId { get; set; }
        public string PropertyTypeName { get; set; }
    
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}
